name: "ðŸš€ release"

on:
    release:
        types: [published]

jobs:
    release:
        name: ðŸš€ release
        runs-on: ubuntu-latest
        steps:
            - name: ðŸ“š checkout
              uses: actions/checkout@v3.5.3
            - name: ðŸŸ¢ node
              uses: actions/checkout@v3.5.3
              with:
                  node-version: 16.13
                  registry-url: https://registry.npmjs.org
            - name: ðŸš€ publish
              run: npm publish --access public
              working-directory: gishka-library
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
